$!
$ DEFINE/NOLOG NETLIB_SHR NETLIB_DIR:NETLIB_SHR
$ DEFINE/NOLOG NETLIB_SHRXFR NETLIB_DIR:NETLIB_SHR
$ DEFINE/NOLOG NETLIB_SSL NETLIB_DIR:NETLIB_SSL
$!
$! COPYRIGHT © 2001, 2004 MADGOAT SOFTWARE.  ALL RIGHTS RESERVED.
$!
